# Generated by Django 5.1.1 on 2024-10-22 02:55

import employee.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_id_card', models.CharField(choices=[('NN', 'No proporciona'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('CC', 'Cedula de ciudadania'), ('TE', 'Tarjeta de extranjeria'), ('CE', 'Cedula de extranjeria'), ('NIT', 'N° Identificacion tributaria'), ('PS', 'Pasaporte'), ('TPE', 'Tipo de documento extranjero')], default='NN', max_length=255, verbose_name='Tipo de identificación')),
                ('image', models.ImageField(blank=True, upload_to=employee.models.employee_image_upload_path, verbose_name='Imagen Perfil')),
                ('phone', models.CharField(max_length=255, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('marital_status', models.CharField(choices=[('NN', 'No registra'), ('S', 'Soltero'), ('C', 'Casado'), ('UL', 'Union Libre')], default='NN', max_length=255, verbose_name='Estado Civil')),
                ('gender', models.CharField(choices=[('NN', 'No registra'), ('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], default='NN', max_length=255, verbose_name='Genero')),
                ('rh', models.CharField(choices=[('NN', 'No registra'), ('O+', 'O Positivo'), ('O-', 'O Negativo'), ('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo')], default='NN', max_length=255, verbose_name='RH')),
                ('role', models.CharField(default='employee', max_length=255, verbose_name='Rol')),
                ('job', models.CharField(default='Servicio', max_length=255, verbose_name='Cargo')),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
