# Generated by Django 5.1.1 on 2024-10-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
