# Generated by Django 5.1.1 on 2024-10-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_card',
            field=models.BigIntegerField(max_length=50, unique=True, verbose_name='Identificación'),
        ),
    ]
