# Generated by Django 5.1.1 on 2025-01-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('NN', 'No registra'), ('ADMIN', 'Administrador'), ('SUBDIRECTOR', 'Subdirector'), ('RECEPTION', 'Recepcionista'), ('TREASURY', 'Tesorería'), ('IT_MANAGER', 'Coordinador de Sistemas'), ('MAINTENANCE', 'Mantenimiento General'), ('MAINTENANCE_TENNIS', 'Mantenimiento de Tenis'), ('MAINTENANCE_GOLF', 'Mantenimiento de Golf'), ('MAINTENANCE_POOL', 'Mantenimiento de Piscina'), ('GOLF_PRO', 'Profesional de Golf'), ('TENNIS_PRO', 'Profesional de Tenis'), ('LIFEGUARD', 'Salvavidas'), ('CHEF', 'Chef'), ('WAITER', 'Mesero'), ('HOUSEKEEPING', 'Servicio de Limpieza'), ('EVENT_MANAGER', 'Gerente de Eventos'), ('SECURITY', 'Seguridad'), ('GARDENER', 'Jardinero'), ('ACCOUNTANT', 'Contador'), ('HR', 'Recursos Humanos'), ('MEMBER_RELATIONS', 'Relaciones con Miembros'), ('COOK', 'Cocinero'), ('HEAD_CHEF', 'Jefe de Cocina'), ('SERVICE_ADMIN', 'Administración de Servicios')], default='NN', max_length=255, verbose_name='Cargo'),
        ),
    ]
