# Generated by Django 5.1.1 on 2025-03-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_address_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.CharField(choices=[('NN', 'No registra'), ('ACCOUNTANT', 'Contador'), ('ADMIN', 'Administrador'), ('ASSISTANT_COOK', 'Auxiliar de Cocina'), ('CHEF', 'Chef'), ('EVENT_MANAGER', 'Gerente de Eventos'), ('GARDENER', 'Jardinero'), ('GOLF_PRO', 'Profesional de Golf'), ('HOUSEKEEPING', 'Servicio de Limpieza'), ('HR', 'Talento Humano'), ('INTERN', 'Pasante'), ('IT_MANAGER', 'Coordinador de Sistemas'), ('LIFEGUARD', 'Salvavidas'), ('MAINTENANCE', 'Mantenimiento General'), ('MAINTENANCE_GOLF', 'Mantenimiento de Golf'), ('MAINTENANCE_POOL', 'Mantenimiento de Piscina'), ('MAINTENANCE_TENNIS', 'Mantenimiento de Tenis'), ('MEMBER_RELATIONS', 'Relaciones con Miembros'), ('RECEPTION', 'Recepcionista'), ('SECURITY', 'Seguridad'), ('SERVICE_ADMIN', 'Administración de Servicios'), ('SERVICE_COORDINATOR', 'Coordinador de Servicios'), ('SUBDIRECTOR', 'Subdirector'), ('TENNNIS_PRO', 'Profesional de Tenis'), ('TREASURY', 'Tesorería'), ('WAITER', 'Mesero'), ('ACCOUNTING', 'Contabilidad')], default='NN', max_length=255, verbose_name='Cargo'),
        ),
    ]
