# Generated by Django 5.1.1 on 2024-10-18 00:09

import employee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to=employee.models.employee_image_upload_path, verbose_name='Imagen Perfil'),
        ),
    ]
