# Generated by Django 5.1.1 on 2024-10-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_card',
            field=models.BigIntegerField(unique=True, verbose_name='Identificación'),
        ),
    ]
