# Generated by Django 5.1.1 on 2024-10-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
    ]
