# Generated by Django 5.1.1 on 2024-10-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_id_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_card',
            field=models.CharField(max_length=25, unique=True, verbose_name='Identificación'),
        ),
    ]
