# Generated by Django 5.1.1 on 2025-01-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Empleado'), ('ADMIN', 'Administrador'), ('SUPERUSER', 'Superusuario')], default='EMPLOYEE', max_length=255, verbose_name='Rol'),
        ),
    ]
