# Generated by Django 5.1.1 on 2024-10-17 22:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_access', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Salida')], max_length=10, verbose_name='Tipo de acceso')),
                ('user_entry', models.DateTimeField(blank=True, null=True, verbose_name='Ingreso')),
                ('user_exit', models.DateTimeField(blank=True, null=True, verbose_name='Salida')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas trabajadas')),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Horas extras')),
                ('qr_data', models.CharField(blank=True, max_length=255, null=True, verbose_name='Codigo QR')),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso',
            },
        ),
    ]
