# Generated by Django 5.1.1 on 2025-03-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeraccess',
            name='extra_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='H. ext diurnas'),
        ),
        migrations.AlterField(
            model_name='registeraccess',
            name='extra_hours_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='H. ext nocturnas'),
        ),
        migrations.AlterField(
            model_name='registeraccess',
            name='hours_worked',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='H. trabajadas'),
        ),
    ]
