# Generated by Django 5.1.1 on 2024-10-08 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('register_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeraccess',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='registeraccess',
            name='employee_entry',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ingreso'),
        ),
        migrations.AlterField(
            model_name='registeraccess',
            name='employee_exit',
            field=models.DateTimeField(auto_now=True, verbose_name='Salida'),
        ),
        migrations.AlterField(
            model_name='registeraccess',
            name='qr_data',
            field=models.CharField(max_length=255, verbose_name='Qr'),
        ),
        migrations.AlterField(
            model_name='registeraccess',
            name='type_access',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Salida')], max_length=10, verbose_name='Tipo de acceso'),
        ),
    ]
