# Generated by Django 5.1.1 on 2025-01-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_access', '0003_registeraccess_extra_hours_night_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeraccess',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
