# Generated by Django 5.1.1 on 2024-10-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_access', '0004_alter_registeraccess_employee_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeraccess',
            name='employee_exit',
            field=models.DateTimeField(auto_now=True, verbose_name='Salida'),
        ),
    ]
