# Generated by Django 5.1.1 on 2024-10-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_access', '0005_alter_registeraccess_employee_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeraccess',
            name='employee_entry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ingreso'),
        ),
        migrations.AlterField(
            model_name='registeraccess',
            name='employee_exit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Salida'),
        ),
    ]
