# Generated by Django 5.1.1 on 2024-10-08 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_access', '0006_alter_registeraccess_employee_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeraccess',
            name='employee_entry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 8, 5, 28, 59, 27040, tzinfo=datetime.timezone.utc), verbose_name='Ingreso'),
        ),
    ]
