services:
  web:
    build: .
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      
    env_file:
      - .env
    depends_on:
      - db
    x-develop:
      watch:
        - path: .
          action: sync 

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ccp_db
      POSTGRES_USER: ronaldjdev
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"  # Exponer el puerto

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./certs/nginx-selfsigned.key:/etc/ssl/certs/nginx-selfsigned.key
    depends_on:
      - web

volumes:
  postgres_data:
